# 进服提示延迟时间 此处单位为秒
sendMessageDelay: 3

'注释52请勿修改': '是否开启PRO版本'
enable_pro: false

'注释53请勿修改': 'PRO版本注册账号名称'
pro_name: xxxxxxxxxxxxxx

'注释54请勿修改': 'PRO版本密钥'
pro_key: xxxxxxxxxxxxxx

'注释1请勿修改': '设置true为使用mysql数据库，设置false为使用yml储存数据'
enableDataBase: false

'注释2请勿修改': '填写你的Host, 默认为Localhost'
host: localhost
'注释3请勿修改': '填写你的Mysql端口, 默认为3306'
port: 3306
'注释4请勿修改': '填写你的用户名，默认为root'
username: root
'注释5请勿修改': '填写你的密码'
password: root
'注释6请勿修改': '填写你需要连接的数据库'
database: minecraft

'注释7请勿修改': '（入服提示）填写你服务器的网址, 没有就填"None"'
joinWebsite: 'None'

'注释8请勿修改': '（侧边栏）记分板标题'
scoreBoardTitle: '欢迎加入服务器'
'注释25请勿修改': '（侧边栏)开关记分板'
enable_scoreboard: true
'注释10请勿修改': '（侧边栏)已关闭记分板的玩家'
player_closed_sb: []

'注释21请勿修改': '是否开启自动版本检查'
enable_version_check: true

'注释56请勿修改': '是否开启自动版本升级(必须同时开启自动版本检查)'
enable_auto_update: false

'注释22请勿修改': '是否开启家功能'
enable_home: true

'注释34请勿修改': '是否开启锁箱子功能'
enable_lock: true

'注释33请勿修改': '是否开启邮件功能'
enable_email: true

'注释32请勿修改': '是否开启入服提示功能'
enable_onjoin: true

'注释35请勿修改': '是否开启远程背包功能'
enable_remote_chest: true

'注释36请勿修改': '是否开启侧边栏显示装备耐久度功能（如果性能不足请关闭这个功能）'
enable_armor_check: true

'注释37请勿修改': '是否开启多世界管理/传送'
enable_multiworlds: true

'注释39请勿修改': '是否开启聊天前缀功能'
enable_chat: true

'注释9请勿修改': '（白名单）开启白名单'
enable_white_list: false

'注释43请勿修改': '（头衔）开启头顶名称前缀后缀显示'
enable_name_prefix: true

'注释46请勿修改': '（登录）是否开启登录功能  (感谢 vang_z 大佬的意见！)'
enable_login: true

'注释47请勿修改': '（礼包）是否开启礼包功能  (感谢 哈德良凯撒 大佬的意见！)'
enable_kits: true

'注释55请勿修改': '（清理）是否开启清理功能  (感谢 绝尘 大佬的意见！)'
enable_cleaner: true

'注释57请勿修改': '（权限）是否开启权限功能  (感谢 绝尘 大佬的意见！)'
enable_permission: true

'注释11请勿修改': '（侧边栏）在安装PlaceholderAPI的情况下生效。空出（""）则为不显示'
'注释12请勿修改': '（侧边栏）开启PAPI变量'
enable_PAPI: false
'注释30请勿修改': '（侧边栏）玩家名字变量'
name: "%player_name%"
'注释40请勿修改': '（侧边栏）在线玩家数变量'
online_player: "%server_online%"
'注释17请勿修改': '（侧边栏）技能冷却值变量'
CDq: "%ul_q_cd%"
CDw: "%ul_w_cd%"
CDe: "%ul_e_cd%"
CDr: "%ul_r_cd%"
'注释13请勿修改': '（侧边栏）玩家现金变量'
money: "%ue_money%"
'注释14请勿修改': '（侧边栏）玩家存款变量'
deposit: "%ue_bank%"
'注释15请勿修改': '（侧边栏）玩家等级变量'
level: "%ul_level%"
'注释16请勿修改': '（侧边栏）玩家目前经验值变量'
exp: "%ul_exp%"
'注释24请勿修改': '（侧边栏）玩家目前最大经验值变量'
max_exp: "%ul_max_exp%"
'注释18请勿修改': '（侧边栏）玩家魔力值变量'
mp: "%ul_mp%"
'注释20请勿修改': '（侧边栏）玩家最大魔力值变量'
max_mp: "%ul_max_mp%"
'注释45请勿修改': '（侧边栏）玩家当前生命值变量'
hp: "%ul_health%"
'注释23请勿修改': '（侧边栏）玩家最大生命值变量'
max_hp: "%ul_max_health%"
'注释19请勿修改': '（侧边栏）玩家职业变量'
occupation: "%ul_job%"
'注释28请勿修改': '（侧边栏）自定义内容'
customerline:
  - '这是自定义的内容'
  - '可以在配置文件里改'
  - '你好，%player_name%'
  - '你甚至可以在里面加上PAPI变量'

'注释26请勿修改': '（锁箱子）OP是否可以打开上锁的箱子（并非解锁，仅查看）'
op_unlock: true
'注释27请勿修改': '（锁箱子）OP是否可以破坏上锁的箱子'
op_break_locked: true

'注释29请勿修改': '（远程背包）创建一个远程背包所需的价格'
price_of_create_a_remote_chest: 10000

'注释38请勿修改': '禁止传送进入的世界'
blocked_worlds: []

'注释41请勿修改': '(chat) 自定义聊天前缀'
chat_prefix: '§e[§a%player_world%§e][§c%ul_job%§dLv.%ul_level%§e][§b%player_name%§e]'

'注释42请勿修改': '(头衔) 自定义头顶显示前缀'
name_prefix: '§e[§c%ul_job%§dLv.%ul_level%§e]'

'注释44请勿修改': '(头衔) 自定义头顶显示后缀'
name_suffix: '§e[§c%ul_health%§e/§c%ul_max_health%§e]'

'注释48请勿修改': '(家) 普通玩家可设置的家上限，0为无限'
home_normal: 3

'注释49请勿修改': '(家) 进阶玩家可设置的家上限，0为无限，权限：ultikits.tools.level1'
home_pro: 5

'注释50请勿修改': '(家) 高级玩家可设置的家上限，0为无限，权限：ultikits.tools.level2'
home_ultimate: 10

'注释51请勿修改': '(家) 家插件传送前等待时间(秒)'
home_tpwait: 3