config_version: 3.11

language: en_US

'comment52': 'if enable PRO version'
enable_pro: false

'comment53': 'PRO version name for register (You cannot change it after registration)'
pro_name: xxxxxxxxxxxxxx

'comment54': 'PRO version Activation Key'
pro_key: xxxxxxxxxxxxxx

'comment1': 'set true to use mysql database, set false to use YAML store data'
enableDataBase: false

'comment2': 'fill with your Host, default is Localhost'
host: localhost
'comment3': 'fill with your Mysql port, default is 3306'
port: 3306
'comment4': 'fill with your username, default is root'
username: root
'comment5': 'fill with your password'
password: root
'comment6': 'fill with the database you want to connect to'
database: minecraft

'comment25': 'enable sidebar'
enable_scoreboard: true

'comment21': 'if enable auto version check'
enable_version_check: true

'comment56': 'if enable auto upgrade (you must also enable auto version check)'
enable_auto_update: false

'comment22': 'if enable Home function'
enable_home: true

'comment34': 'if enable Chest Lock function'
enable_lock: true

'comment33': 'if enable Email function'
enable_email: true

'comment32': 'if enable Join Welcome function'
enable_onjoin: true

'comment35': 'if enable Remote Bag function'
enable_remote_chest: true

'comment36': 'if enable sidebar display armor durability function（if performs bad please close this function）'
enable_armor_check: true

'comment37': 'if enable multi-worlds manage/teleport'
enable_multiworlds: true

'comment39': 'if enable chat prefix function'
enable_chat: true

'comment9': 'enable whitelist'
enable_white_list: false

'comment43': 'enable above-head prefix suffix display '
enable_name_prefix: true

'comment46': 'if enable Login function'
enable_login: true

'comment47': 'if enable Kits function'
enable_kits: true

'comment55': 'if enable Cleaner function'
enable_cleaner: true

'comment57': 'if enable Permission Management function'
enable_permission: true

'comment12': 'enable PAPI'
enable_PAPI: false

'comment13': 'enable Death Punishment function'
enable_death_punishment: true

'comment14': 'enable social system'
enable_social_system: true

'comment15': 'enable tpa function'
enable_tpa: true

'comment29': '(Remote bag) Price to create a bag'
price_of_create_a_remote_chest: 10000

'comment41': '(chat) customize chat prefix'
chat_prefix: '§e[§a%player_world%§e][§c%ul_job%§dLv.%ul_level%§e][§b%player_name%§e]'

'comment42': 'customize above-head display prefix'
name_prefix: '§e[§c%ul_job%§dLv.%ul_level%§e]'

'comment44': 'customize above-head display suffix'
name_suffix: '§e[§c%ul_health%§e/§c%ul_max_health%§e]'