name: UltiTools-geyser
version: ${project.version}
main: com.ultikits.ultitools.ultitools.UltiTools
api-version: 1.13
depend: [ PlaceholderAPI, Vault, UltiCore, floodgate]
authors: [ wisdomme, qianmo,EnderLight3336 ]
website: ultikits.com

commands:
  ultitools:
    description: UltiTools Commands
    usage: /ultitools help