# 进服提示延迟时间 此处单位为秒
sendMessageDelay: 3

'注释1请勿修改': '设置true为使用mysql数据库，设置false为使用yml储存数据'
enableDataBase: false

'注释2请勿修改': '填写你的Host, 默认为Localhost'
host: localhost
'注释3请勿修改': '填写你的Mysql端口, 默认为3306'
port: 3306
'注释4请勿修改': '填写你的用户名，默认为root'
username: root
'注释5请勿修改': '填写你的密码'
password: root
'注释6请勿修改': '填写你需要连接的数据库'
database: minecraft

'注释7请勿修改': '（入服提示）填写你服务器的网址, 没有就填"None"'
joinWebsite: 'None'

'注释8请勿修改': '（侧边栏）记分板标题'
scoreBoardTitle: '欢迎加入服务器'