# 进服提示延迟时间 此处单位为秒
sendMessageDelay: 3

'注释1请勿修改': '设置true为使用mysql数据库，设置false为使用yml储存数据'
enableDataBase: false

'注释2请勿修改': '填写你的Host, 默认为Localhost'
host: localhost
'注释3请勿修改': '填写你的Mysql端口, 默认为3306'
port: 3306
'注释4请勿修改': '填写你的用户名，默认为root'
username: root
'注释5请勿修改': '填写你的密码'
password: root
'注释6请勿修改': '填写你需要连接的数据库'
database: minecraft

'注释7请勿修改': '（入服提示）填写你服务器的网址, 没有就填"None"'
joinWebsite: 'None'

'注释8请勿修改': '（侧边栏）记分板标题'
scoreBoardTitle: '欢迎加入服务器'
'注释10请勿修改': '（侧边栏)已关闭记分板的玩家'
player_closed_sb: []

'注释21请勿修改': '是否开启自动版本检查'
enable_version_check: false

'注释9请勿修改': '（白名单）开启白名单'
enable_white_list: false

'注释11请勿修改': '（侧边栏）在安装PlaceholderAPI的情况下生效。空出（""）则为不显示'
'注释12请勿修改': '（侧边栏）技能变量'
enable_PAPI: false
'注释17请勿修改': '（侧边栏）技能冷却值变量'
CDq: "%ul_q_cd%"
CDw: "%ul_w_cd%"
CDe: "%ul_e_cd%"
CDr: "%ul_r_cd%"
'注释13请勿修改': '（侧边栏）玩家现金变量'
money: "%ue_money%"
'注释14请勿修改': '（侧边栏）玩家存款变量'
deposit: "%ue_bank%"
'注释15请勿修改': '（侧边栏）玩家等级变量'
level: "%ul_level%"
'注释16请勿修改': '（侧边栏）玩家目前经验值变量'
exp: "%ul_exp%"
'注释18请勿修改': '（侧边栏）玩家魔力值变量'
mp: "%ul_mp%"
'注释20请勿修改': '（侧边栏）玩家最大魔力值变量'
max_mp: ""
'注释19请勿修改': '（侧边栏）玩家职业变量'
occupation: "%ul_job%"