name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.github/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload built jar
      uses: actions/upload-artifact@v2
      with:
        name: UltiTools
        path: target/UltiTools-**.jar
